ansible_ssh_user: admin
ansible_ssh_pass: YourPaSsWoRd
ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o ConnectTimeout=30"
ansible_network_os: dellemc.enterprise_sonic.sonic
ansible_become_password: YourPaSsWoRd
# Additional parameters for connection type httpapi
#

