---
switch_role: leaf

sonic_vlans:
  - vlan_id: 16
  - vlan_id: 12
  - vlan_id: 1100
  - vlan_id: 1200

sonic_l3_interfaces:
  - name: VLAN_Prod_11
    ipv4:
      anycast_addresses:
        - 192.168.11.254/24
  - name: VLAN_Prod_12
    ipv4:
      anycast_addresses:
        - 192.168.12.254/24

sonic_l2_interfaces:
  - name: Eth1/3
    access:
      vlan: 11
  - name: Po100
    trunk:
      allowed_vlans:
        - vlan: 11
        - vlan: 12
  - name: Eth1/4
    access:
      vlan: 12

sonic_vrfs:
  - name: Vrf1
    members:
      interfaces:
        - name: Vlan11
        - name: Vlan12
        - name: Vlan1100
  - name: Vrf2
    members:
      interfaces:
        - name: Vlan1200

sonic_vxlans:
  - name: vtep1
    source_ip: 10.1.0.1
    evpn_nvo: nvo1
    vlan_map:
      - vni: 10011
        vlan: 11
      - vni: 10012
        vlan: 12
      - vni: 11100
        vlan: 1100
      - vni: 11200
        vlan: 1200
    vrf_map:
      - vni: 11200
        vrf: Vrf2
